# Generated by Django 5.2.7 on 2025-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0002_product_lead_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='probability_of_completion',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=0, help_text='Probability of closing this deal (set once at lead creation)'),
        ),
    ]
