# Generated by Django 5.2.7 on 2025-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0003_lead_probability_of_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['division', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='division',
            field=models.CharField(choices=[('tech', 'Gralix Tech'), ('actuarial', 'Gralix Actuarial'), ('capital', 'Gralix Capital')], default='tech', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'division')},
        ),
    ]
