# Generated by Django 4.2.7 on 2026-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0005_team_remove_personnel_workload_lead_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
