# Generated by Django 4.2.7 on 2026-01-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0006_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='quality_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
