# Generated by Django 4.2.7 on 2026-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0007_lead_quality_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_leads', models.IntegerField(default=0)),
                ('total_pipeline_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_lead_quality', models.IntegerField(default=0, help_text='Average Lead IQ score')),
                ('stage_distribution', models.JSONField(default=dict, help_text='Count of leads by status')),
                ('division_distribution', models.JSONField(default=dict, help_text='Count of leads by division')),
                ('source_distribution', models.JSONField(blank=True, default=dict, help_text='Count of leads by source (if tracked)')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
