# Generated by Django 4.2.7 on 2026-01-25 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0008_dailysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard daily rate for this personnel', max_digits=10),
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Role in this specific project', max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate at time of assignment', max_digits=10)),
                ('days_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='gralix_lead.lead')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item description', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_costs', to='gralix_lead.lead')),
            ],
        ),
    ]
