# Generated by Django 4.2.7 on 2026-01-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('agent', 'Sales Agent'), ('executive', 'Executive Manager')], default='agent', max_length=20),
        ),
    ]
