# Generated by Django 5.2.4 on 2025-07-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('hot', 'Hot'), ('won', 'Won'), ('lost', 'Lost'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('division', models.CharField(choices=[('tech', 'Gralix Tech'), ('actuarial', 'Gralix Actuarial'), ('capital', 'Gralix Capital')], max_length=20)),
                ('deal_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('tech', 'Gralix Tech'), ('actuarial', 'Gralix Actuarial'), ('capital', 'Gralix Capital')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('workload', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Demo/Presentation'), ('proposal', 'Proposal Sent'), ('followup', 'Follow-up'), ('reassignment', 'Reassignment')], max_length=20)),
                ('note', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='gralix_lead.lead')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gralix_lead.personnel'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gralix_lead.lead')),
                ('from_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from', to='gralix_lead.personnel')),
                ('to_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to', to='gralix_lead.personnel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
