# Generated by Django 5.2.4 on 2025-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gralix_lead', '0002_alter_personnel_options_alter_personnel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='division',
            field=models.CharField(blank=True, choices=[('tech', 'Gralix Tech'), ('actuarial', 'Gralix Actuarial'), ('capital', 'Gralix Capital')], max_length=20, null=True),
        ),
    ]
